version: '3.7'

services:
  mongo:
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
    env_file:
      - .env
    depends_on:
      - broker

  broker:
    image: nats-streaming:0.20-alpine
    command: -cid broker
    ports:
      - 4222:4222

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - node_modules
      - ./:/usr/src/app
    depends_on:
      - broker
      - mongo
      - prometheus

volumes:
  deps:
